services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - pdf_service

  pdf_service:
    build:
      context: ./pdf_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
